spring.application.name=facens

#POSTGRE SUPABASE
spring.datasource.url=jdbc:postgresql://db.jesnklizldnogatzzgku.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=TWDdr1ppLz1k4*

spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
